# Make a modelling dataframe
```{python}
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#from pcntoolkit import (BLR,NormativeModel,NormData,plot_centiles,plot_qq,)
#import pcntoolkit.util.output

current_dir = Path.cwd().parent
combined_path = current_dir / "results" / "combined_dataset" / "Combined_dataset.csv"

model_df = pd.read_csv(combined_path)

print("Combined dataset shape:", model_df.shape)

components = [f"comp{i}" for i in range(1, 19)]

# Components numeric
for component in components:
    model_df[component] = pd.to_numeric(
        model_df[component],
        errors="coerce"
    )

id_columns = ["Scan_id","Participant_Id"]

batch_effects = ["Dataset_name"]

covariates = [
    "Session",
    "Sex",
    "Age(week)",
    "Rodent.strain",
    "MRI",
    "Coil",
    "fMRI.sequence",
    "MRI T.R.",
    "MRI T.E.",
    "Anethesia",
    "Anesthesia amount",
    "Ventilation",
    "head-plate",
    "Habituation",
    "FD average",
    "FD maximum",
    "tSNR"
]

response_vars = components

encoding_table = []

# Encode string covariates
for col in covariates:
    if model_df[col].dtype == "str":
        values = model_df[col].dropna().unique()

        print(values)  
```
        # Binary categorical variable
        if len(values) == 2:

            model_df[col + "_encoded"] = model_df[col].map({
                values[0]: 0,
                values[1]: 1
            })

            encoding_table.append([col, values[0], 0])
            encoding_table.append([col, values[1], 1])

            covariates.remove(col)
            covariates.append(col + "_encoded")

        # More than 2 categories
        else:

            dummies = pd.get_dummies(
                model_df[col],
                prefix=col,
                dtype=float
            )

            model_df = pd.concat(
                [model_df, dummies],
                axis=1
            )

            for dummy in dummies.columns:
                encoding_table.append([
                    col,
                    dummy.replace(col + "_", ""),
                    dummy
                ])

            covariates.remove(col)
            covariates.extend(dummies.columns.tolist())


encoding_table = pd.DataFrame(
    encoding_table,
    columns=[
        "Variable",
        "Category",
        "Encoding"
    ]
)

print("\nCovariates:")
print(covariates)

print("\nBatch effects:")
print(batch_effects)

print("\nResponse variables:")
print(response_vars)

print("\nEncoding table:")
display(encoding_table)